### ISSUE TITLE
Support multi-word insultees

### ISSUE THREAD

**Issue by richardsonj** [theArgo15/bullyBot#2]
I might want to insult something that is more complex than a single word or name.
I suggest using a period to separate the insultee, and any flavor text you'd like to add. (Although, that could be in issue if you wanted to insult Dr. Phil)
Examples:
!insult that guy from that one show on tv. I hate him so much I can't even remember his name or the show he's on
Resulting insultee "that guy from that one show on tv"

**Comment by theArgo15** [comment]
Fixing in next release. If you need to insult Dr. Phil, call him Dr Phil.

**Comment by theArgo15** [comment]
c7da654
